#spring:
#  # 配置数据源
#  shardingsphere:
#    datasource:
#      names: ds0
#      ds0:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driverClassName: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://10.10.49.18:3306/ibs5_environment?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&useSSL=true
#        #        url: jdbc:mysql://localhost:3306/ews?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&useSSL=true
#        username: root
#        password: root123
#    sharding:
#      tables:
#        tbl_history_moment:
#          actualDataNodes: ds0.tbl_history_moment
#          tableStrategy:
#            hint:
#              algorithmClassName: com.thtf.environment.common.config.HintShardingTableAlgorithm
#    props:
#      sql:
#        show: true

feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        requestInterceptors: com.thtf.environment.common.feign.FeignBasicAuthRequestInterceptor

#
#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  type-aliases-package: com.thtf.environment.entity

management:
  health:
    db:
      enabled: false