# 数据库配置
#spring:
#  # 配置数据源
#  datasource:
#    url: jdbc:mysql://10.10.49.18:3306/kl_hospital?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: root123
#    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  # 配置数据源
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.10.49.18:3306/ibs5_environment?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&useSSL=true
        username: root
        password: root123
    sharding:
      tables:
        tbl_history_moment:
          actualDataNodes: ds0.tbl_history_moment
          tableStrategy:
            hint:
              algorithmClassName: com.thtf.environment.commons.config.HintShardingTableAlgorithm
    props:
      sql:
        show: true
# 对feign的请求进行拦截和求情方法保留
feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        requestInterceptors: com.thtf.environment.common.feign.FeignBasicAuthRequestInterceptor


