spring:
  datasource:
    url: jdbc:mysql://10.10.49.18:3306/kl_hospital?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        requestInterceptors: com.thtf.face_recognition.common.feign.FeignBasicAuthRequestInterceptor
